services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bubblebrain-app
    env_file:
      - .env
    ports:
      - "8200:8000" # Зовнішній порт 8200 мапиться на внутрішній 8000
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: bubblebrain-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=https://alliases.duckdns.org/BubbleBrain/prometheus/'
    ports:
      - "9290:9090"
    restart: unless-stopped
