import uuid
from collections.abc import AsyncGenerator

from fastapi import APIRouter, Depends, Request
from fastapi.responses import StreamingResponse

from app.api.dependencies import get_rag_engine
from app.core.constants import MSG_STREAM_CHAT_FAILED, MSG_SYNC_CHAT_FAILED
from app.core.logging_config import get_logger
from app.core.metrics import bot_messages_total
from app.core.security import verify_api_key
from app.middleware.rate_limiter import limiter
from app.schemas.chat import ChatRequest, ChatResponse
from app.services.rag_engine import RAGEngine
from app.utils.network import get_client_ip

logger = get_logger(__name__)
chat_router = APIRouter()


@chat_router.post("", response_model=ChatResponse)
@limiter.limit("20/minute")  # type: ignore
async def chat_completion(
    request: Request,
    chat_request: ChatRequest,
    api_key: str = Depends(verify_api_key),
    rag_engine: RAGEngine = Depends(get_rag_engine),
) -> ChatResponse:
    """
    Synchronous chat endpoint. Runs the RAG pipeline and returns the full response.
    """
    client_ip = get_client_ip(request)
    logger.info(
        "Sync chat request received", session_id=chat_request.session_id, client_ip=client_ip
    )
    session_id = chat_request.session_id or str(uuid.uuid4())

    try:
        rag_response = await rag_engine.process_query(
            chat_request.question, session_id=session_id, client_ip=client_ip
        )
        bot_messages_total.labels(status="success").inc()
        return ChatResponse(  # type: ignore[call-arg]
            answer=rag_response.answer,
            sources=rag_response.sources,
            has_context=rag_response.has_context,
            session_id=session_id,
        )
    except Exception as e:
        bot_messages_total.labels(status="error").inc()
        logger.error("Critical error in sync chat pipeline", error=str(e), exc_info=True)
        # Fallback response instead of 500 error
        return ChatResponse(  # type: ignore[call-arg]
            answer=MSG_SYNC_CHAT_FAILED,
            sources=[],
            has_context=False,
            session_id=session_id,
        )


@chat_router.post("/stream")
@limiter.limit("20/minute")  # type: ignore[reportUntypedFunctionDecorator, reportUnknownMemberType]
async def chat_stream(
    request: Request,
    chat_request: ChatRequest,
    api_key: str = Depends(verify_api_key),
    rag_engine: RAGEngine = Depends(get_rag_engine),
) -> StreamingResponse:
    """
    Streaming (SSE) chat endpoint. Returns tokens as they are generated by the model.
    """
    client_ip = get_client_ip(request)
    session_id = chat_request.session_id or str(uuid.uuid4())
    logger.info("Stream chat request received", session_id=session_id, client_ip=client_ip)

    async def event_generator() -> AsyncGenerator[str]:
        try:
            async for token in rag_engine.process_query_stream(
                chat_request.question, session_id=session_id, client_ip=client_ip
            ):
                yield f"data: {token}\n\n"
            bot_messages_total.labels(status="success").inc()
        except Exception as e:
            bot_messages_total.labels(status="error").inc()
            logger.error("Critical error during streaming", error=str(e), exc_info=True)
            yield f"data: {MSG_STREAM_CHAT_FAILED}\n\n"
        finally:
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(), media_type="text/event-stream", headers={"X-Accel-Buffering": "no"}
    )
